version: '3'
services:
  backend:
    container_name: cmp-backend
    build: ./backend
    command: yarn dev
    volumes:
      - ./backend:/backend
    ports:
      - '3001:3001'
    links:
      - database
  admin:
    container_name: cmp-admin
    build: ./admin
    volumes:
      - ./admin:/admin
    ports:
      - '3002:3002'
    links:
      - backend
  users:
    container_name: cmp-users
    build: ./users
    volumes:
      - ./users:/users
    ports:
      - '3000:3000'
  database:
    container_name: 'cmp-database'
    build: ./database
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
